name: Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - uses: actions/setup-node@v2
        with:
          node-version: 14.19.0
          cache: 'pnpm'

      - name: install
        run: pnpm install

      - name: lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - uses: actions/setup-node@v2
        with:
          node-version: 14.19.0
          cache: 'pnpm'

      - name: install
        run: pnpm install

      - name: build
        run: npm run build

      - name: Set up QEMU
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-buildx-action@v1

      - name: login to docker hub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        # 配置登录信息，secrets 变量在 github settings -> secrets 中设置
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
